### ISSUE TITLE
Agent telegraf configuration fail

### ISSUE THREAD

**Issue by aileo** [bleemeo/bleemeo-agent#2]
Step to reproduce :
- Create new service with `type: nagios` and no `address`
- Start bleemeo-agent

Result (syslog):
`WARNING - Failed to write telegraf configuration. Continuing with current configuration`

And with debug level :
```
DEBUG - exception is:
#012Traceback (most recent call last):
#012  File "/usr/lib/python3/dist-packages/bleemeo_agent/telegraf.py", line 217, in update_discovery
#012    self._write_config()
#012  File "/usr/lib/python3/dist-packages/bleemeo_agent/telegraf.py", line 225, in _write_config
#012    telegraf_config = self._get_telegraf_config()
#012  File "/usr/lib/python3/dist-packages/bleemeo_agent/telegraf.py", line 286, in _get_telegraf_config
#012    if service_info['address'] is None and instance is not None:
#012KeyError: 'address'
```

**Comment by PierreF** [comment]
Hi,

I've missed this issue, but it should be fixed by commit b205c2b.
If the issue persist feel free to reopen this ticket.
